# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Peak Dad
tagline:          'The over-the-top dad blog'
description:      'The over-the-top dad blog'
url:              https://peakdad.com
baseurl:          /

author:
  name:           'Nico Boyce'
  url:            https://peakdad.com

# paginate:         4

# plugins:
#  - jekyll-paginate-v2
#  - jekyll-gist

# Custom vars
version:          24.05

excerpt_separator: "<!--excerpt-end-->"
# github:
#   repo:           https://github.com/poole/hyde
